# Generated by Django 6.0.8 on 2026-08-20 17:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('renovation', 'Renovation'), ('industrial', 'Industrial')], max_length=24)),
                ('location', models.CharField(max_length=160)),
                ('summary', models.CharField(max_length=260)),
                ('description', models.TextField()),
                ('client_name', models.CharField(blank=True, max_length=120)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('duration_months', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('area_sqm', models.PositiveIntegerField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-completion_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='01', help_text='Short number or symbol displayed on the service card.', max_length=12)),
                ('image_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('client_role', models.CharField(blank=True, max_length=160)),
                ('quote', models.TextField(max_length=600)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=160)),
                ('project_type', models.CharField(choices=[('new_home', 'New home construction'), ('commercial', 'Commercial construction'), ('renovation', 'Renovation / fit-out'), ('extension', 'House extension'), ('industrial', 'Industrial project'), ('other', 'Other')], max_length=30)),
                ('location', models.CharField(max_length=220)),
                ('budget', models.CharField(choices=[('under_1m', 'Below ₱1 million'), ('1m_3m', '₱1–3 million'), ('3m_5m', '₱3–5 million'), ('5m_10m', '₱5–10 million'), ('above_10m', 'Above ₱10 million'), ('discuss', 'To be discussed')], max_length=30)),
                ('timeline', models.CharField(choices=[('asap', 'As soon as possible'), ('1_3_months', 'Within 1–3 months'), ('3_6_months', 'Within 3–6 months'), ('6_plus_months', 'After 6 months'), ('flexible', 'Flexible')], max_length=30)),
                ('details', models.TextField()),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone call'), ('sms', 'SMS')], default='email', max_length=16)),
                ('status', models.CharField(choices=[('new', 'New request'), ('reviewing', 'Under review'), ('consultation', 'Consultation scheduled'), ('proposal_sent', 'Proposal sent'), ('approved', 'Approved'), ('in_progress', 'Project in progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='new', max_length=24)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New request'), ('reviewing', 'Under review'), ('consultation', 'Consultation scheduled'), ('proposal_sent', 'Proposal sent'), ('approved', 'Approved'), ('in_progress', 'Project in progress'), ('completed', 'Completed'), ('closed', 'Closed')], max_length=24)),
                ('note', models.CharField(blank=True, max_length=400)),
                ('client_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_updates', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.quoterequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
